# Generated by Django 5.0.6 on 2024-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('tripulantes', models.CharField(max_length=1)),
            ],
        ),
    ]
